[2023-05-13T21:16:10.275+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ny_taxi_local.create_directory.print_user manual__2023-05-13T21:16:08.980467+00:00 [queued]>
[2023-05-13T21:16:10.284+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ny_taxi_local.create_directory.print_user manual__2023-05-13T21:16:08.980467+00:00 [queued]>
[2023-05-13T21:16:10.285+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T21:16:10.285+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-13T21:16:10.286+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T21:16:10.297+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): create_directory.print_user> on 2023-05-13 21:16:08.980467+00:00
[2023-05-13T21:16:10.303+0000] {standard_task_runner.py:55} INFO - Started process 846 to run task
[2023-05-13T21:16:10.307+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ny_taxi_local', 'create_directory.print_user', 'manual__2023-05-13T21:16:08.980467+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/fetch_and_upload.py', '--cfg-path', '/tmp/tmpcqztmz_j']
[2023-05-13T21:16:10.309+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask create_directory.print_user
[2023-05-13T21:16:10.404+0000] {task_command.py:389} INFO - Running <TaskInstance: ny_taxi_local.create_directory.print_user manual__2023-05-13T21:16:08.980467+00:00 [running]> on host fdfc81637e26
[2023-05-13T21:16:10.464+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ny_taxi_local
AIRFLOW_CTX_TASK_ID=create_directory.print_user
AIRFLOW_CTX_EXECUTION_DATE=2023-05-13T21:16:08.980467+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-13T21:16:08.980467+00:00
[2023-05-13T21:16:10.467+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_and_upload.py", line 34, in print_user
    print(os.getlogin())
OSError: [Errno 6] No such device or address
[2023-05-13T21:16:10.478+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=ny_taxi_local, task_id=create_directory.print_user, execution_date=20230513T211608, start_date=20230513T211610, end_date=20230513T211610
[2023-05-13T21:16:10.487+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 25 for task create_directory.print_user ([Errno 6] No such device or address; 846)
[2023-05-13T21:16:10.520+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-13T21:16:10.544+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
