[2023-05-13T22:21:34.589+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ny_taxi_local.get_data.bash_get_data manual__2023-05-13T22:18:38.904891+00:00 [queued]>
[2023-05-13T22:21:34.595+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ny_taxi_local.get_data.bash_get_data manual__2023-05-13T22:18:38.904891+00:00 [queued]>
[2023-05-13T22:21:34.596+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T22:21:34.596+0000] {taskinstance.py:1289} INFO - Starting attempt 2 of 2
[2023-05-13T22:21:34.597+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T22:21:34.605+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): get_data.bash_get_data> on 2023-05-13 22:18:38.904891+00:00
[2023-05-13T22:21:34.609+0000] {standard_task_runner.py:55} INFO - Started process 2577 to run task
[2023-05-13T22:21:34.613+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ny_taxi_local', 'get_data.bash_get_data', 'manual__2023-05-13T22:18:38.904891+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/fetch_and_upload.py', '--cfg-path', '/tmp/tmpznqdz8tv']
[2023-05-13T22:21:34.615+0000] {standard_task_runner.py:83} INFO - Job 81: Subtask get_data.bash_get_data
[2023-05-13T22:21:34.668+0000] {task_command.py:389} INFO - Running <TaskInstance: ny_taxi_local.get_data.bash_get_data manual__2023-05-13T22:18:38.904891+00:00 [running]> on host fdfc81637e26
[2023-05-13T22:21:34.728+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ny_taxi_local
AIRFLOW_CTX_TASK_ID=get_data.bash_get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-05-13T22:18:38.904891+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-13T22:18:38.904891+00:00
[2023-05-13T22:21:34.731+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-13T22:21:34.732+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.csv.gz > yellow_tripdata_2021-01.csv.gz']
[2023-05-13T22:21:34.741+0000] {subprocess.py:86} INFO - Output:
[2023-05-13T22:21:34.956+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-05-13T22:21:34.960+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_and_upload.py", line 64, in bash_get_data
    os.rename(f'{dataset_file}', new_file_name)
FileNotFoundError: [Errno 2] No such file or directory: 'yellow_tripdata_2021-01.csv.gz' -> 'yellow_tripdata_2023-05-13-22-21-34.csv.gz'
[2023-05-13T22:21:34.984+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=ny_taxi_local, task_id=get_data.bash_get_data, execution_date=20230513T221838, start_date=20230513T222134, end_date=20230513T222134
[2023-05-13T22:21:35.000+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 81 for task get_data.bash_get_data ([Errno 2] No such file or directory: 'yellow_tripdata_2021-01.csv.gz' -> 'yellow_tripdata_2023-05-13-22-21-34.csv.gz'; 2577)
[2023-05-13T22:21:35.032+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-13T22:21:35.049+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
