[2023-06-23T01:58:35.723+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T01:57:31.696804+00:00 [queued]>
[2023-06-23T01:58:35.729+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T01:57:31.696804+00:00 [queued]>
[2023-06-23T01:58:35.730+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T01:58:35.730+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-23T01:58:35.731+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T01:58:35.739+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-23 01:57:31.696804+00:00
[2023-06-23T01:58:35.742+0000] {standard_task_runner.py:55} INFO - Started process 24542 to run task
[2023-06-23T01:58:35.746+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'showpulse_dbt_dag', 'dbt_run', 'scheduled__2023-06-23T01:57:31.696804+00:00', '--job-id', '2662', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run.py', '--cfg-path', '/tmp/tmpbp11jkt4']
[2023-06-23T01:58:35.746+0000] {standard_task_runner.py:83} INFO - Job 2662: Subtask dbt_run
[2023-06-23T01:58:35.799+0000] {task_command.py:389} INFO - Running <TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T01:57:31.696804+00:00 [running]> on host 62cfed75eae1
[2023-06-23T01:58:35.848+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nburkett
AIRFLOW_CTX_DAG_ID=showpulse_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-23T01:57:31.696804+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-23T01:57:31.696804+00:00
[2023-06-23T01:58:35.849+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-23T01:58:35.850+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/ticketmaster_transformation && dbt run']
[2023-06-23T01:58:35.857+0000] {subprocess.py:86} INFO - Output:
[2023-06-23T01:58:37.140+0000] {subprocess.py:93} INFO - [0m01:58:37  Running with dbt=1.5.1
[2023-06-23T01:58:37.638+0000] {subprocess.py:93} INFO - [0m01:58:37  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 356 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-23T01:58:37.642+0000] {subprocess.py:93} INFO - [0m01:58:37
[2023-06-23T01:58:38.239+0000] {subprocess.py:93} INFO - [0m01:58:38  Concurrency: 4 threads (target='dev')
[2023-06-23T01:58:38.242+0000] {subprocess.py:93} INFO - [0m01:58:38
[2023-06-23T01:58:38.257+0000] {subprocess.py:93} INFO - [0m01:58:38  1 of 4 START sql table model twitter_kafka_pyspark_test.distinct_data .......... [RUN]
[2023-06-23T01:58:38.259+0000] {subprocess.py:93} INFO - [0m01:58:38  2 of 4 START sql table model twitter_kafka_pyspark_test.dm_events .............. [RUN]
[2023-06-23T01:58:38.261+0000] {subprocess.py:93} INFO - [0m01:58:38  3 of 4 START sql table model twitter_kafka_pyspark_test.my_first_dbt_model ..... [RUN]
[2023-06-23T01:58:40.620+0000] {subprocess.py:93} INFO - [0m01:58:40  BigQuery adapter: https://console.cloud.google.com/bigquery?project=global-maxim-338114&j=bq:US:635a4150-600f-43ef-9921-ea217c9ba9b2&page=queryresults
[2023-06-23T01:58:40.650+0000] {subprocess.py:93} INFO - [0m01:58:40  2 of 4 ERROR creating sql table model twitter_kafka_pyspark_test.dm_events ..... [[31mERROR[0m in 2.38s]
[2023-06-23T01:58:40.843+0000] {subprocess.py:93} INFO - [0m01:58:40  1 of 4 OK created sql table model twitter_kafka_pyspark_test.distinct_data ..... [[32mCREATE TABLE (1.0 rows, 0 processed)[0m in 2.57s]
[2023-06-23T01:58:49.793+0000] {subprocess.py:93} INFO - [0m01:58:49  3 of 4 OK created sql table model twitter_kafka_pyspark_test.my_first_dbt_model  [[32mCREATE TABLE (2.0 rows, 0 processed)[0m in 11.53s]
[2023-06-23T01:58:49.800+0000] {subprocess.py:93} INFO - [0m01:58:49  4 of 4 START sql view model twitter_kafka_pyspark_test.my_second_dbt_model ..... [RUN]
[2023-06-23T01:58:50.844+0000] {subprocess.py:93} INFO - [0m01:58:50  4 of 4 OK created sql view model twitter_kafka_pyspark_test.my_second_dbt_model  [[32mCREATE VIEW (0 processed)[0m in 1.04s]
[2023-06-23T01:58:50.928+0000] {subprocess.py:93} INFO - [0m01:58:50
[2023-06-23T01:58:50.930+0000] {subprocess.py:93} INFO - [0m01:58:50  Finished running 3 table models, 1 view model in 0 hours 0 minutes and 13.29 seconds (13.29s).
[2023-06-23T01:58:50.953+0000] {subprocess.py:93} INFO - [0m01:58:50
[2023-06-23T01:58:50.956+0000] {subprocess.py:93} INFO - [0m01:58:50  [31mCompleted with 1 error and 0 warnings:[0m
[2023-06-23T01:58:50.957+0000] {subprocess.py:93} INFO - [0m01:58:50
[2023-06-23T01:58:50.958+0000] {subprocess.py:93} INFO - [0m01:58:50  [33mDatabase Error in model dm_events (models/core/dm_events.sql)[0m
[2023-06-23T01:58:50.960+0000] {subprocess.py:93} INFO - [0m01:58:50    Unrecognized name: event_id at [14:8]
[2023-06-23T01:58:50.961+0000] {subprocess.py:93} INFO - [0m01:58:50    compiled Code at target/run/ticketmaster_transformation/models/core/dm_events.sql
[2023-06-23T01:58:50.962+0000] {subprocess.py:93} INFO - [0m01:58:50
[2023-06-23T01:58:50.963+0000] {subprocess.py:93} INFO - [0m01:58:50  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
[2023-06-23T01:58:51.456+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-23T01:58:51.475+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-23T01:58:51.481+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=showpulse_dbt_dag, task_id=dbt_run, execution_date=20230623T015731, start_date=20230623T015835, end_date=20230623T015851
[2023-06-23T01:58:51.495+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2662 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 24542)
[2023-06-23T01:58:51.513+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-23T01:58:51.530+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
