[2023-05-13T21:13:06.964+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ny_taxi_local.create_directory.print_user manual__2023-05-13T21:13:05.779069+00:00 [queued]>
[2023-05-13T21:13:06.971+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ny_taxi_local.create_directory.print_user manual__2023-05-13T21:13:05.779069+00:00 [queued]>
[2023-05-13T21:13:06.972+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T21:13:06.973+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-13T21:13:06.973+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T21:13:06.982+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): create_directory.print_user> on 2023-05-13 21:13:05.779069+00:00
[2023-05-13T21:13:06.988+0000] {standard_task_runner.py:55} INFO - Started process 763 to run task
[2023-05-13T21:13:06.992+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ny_taxi_local', 'create_directory.print_user', 'manual__2023-05-13T21:13:05.779069+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/fetch_and_upload.py', '--cfg-path', '/tmp/tmp3qgwfz_j']
[2023-05-13T21:13:06.995+0000] {standard_task_runner.py:83} INFO - Job 22: Subtask create_directory.print_user
[2023-05-13T21:13:07.081+0000] {task_command.py:389} INFO - Running <TaskInstance: ny_taxi_local.create_directory.print_user manual__2023-05-13T21:13:05.779069+00:00 [running]> on host fdfc81637e26
[2023-05-13T21:13:07.140+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ny_taxi_local
AIRFLOW_CTX_TASK_ID=create_directory.print_user
AIRFLOW_CTX_EXECUTION_DATE=2023-05-13T21:13:05.779069+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-13T21:13:05.779069+00:00
[2023-05-13T21:13:07.143+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_and_upload.py", line 34, in print_user
    print(os.getlogin())
OSError: [Errno 6] No such device or address
[2023-05-13T21:13:07.154+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=ny_taxi_local, task_id=create_directory.print_user, execution_date=20230513T211305, start_date=20230513T211306, end_date=20230513T211307
[2023-05-13T21:13:07.163+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 22 for task create_directory.print_user ([Errno 6] No such device or address; 763)
[2023-05-13T21:13:07.207+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-13T21:13:07.236+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
