[2023-06-17T21:00:53.130+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_initiate manual__2023-06-17T21:00:52.557322+00:00 [queued]>
[2023-06-17T21:00:53.136+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_initiate manual__2023-06-17T21:00:52.557322+00:00 [queued]>
[2023-06-17T21:00:53.136+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-17T21:00:53.137+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-17T21:00:53.137+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-17T21:00:53.146+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): dbt_initiate> on 2023-06-17 21:00:52.557322+00:00
[2023-06-17T21:00:53.149+0000] {standard_task_runner.py:55} INFO - Started process 84 to run task
[2023-06-17T21:00:53.153+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'showpulse_dbt_dag', 'dbt_initiate', 'manual__2023-06-17T21:00:52.557322+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run.py', '--cfg-path', '/tmp/tmpoalyrdvb']
[2023-06-17T21:00:53.154+0000] {standard_task_runner.py:83} INFO - Job 262: Subtask dbt_initiate
[2023-06-17T21:00:53.205+0000] {task_command.py:389} INFO - Running <TaskInstance: showpulse_dbt_dag.dbt_initiate manual__2023-06-17T21:00:52.557322+00:00 [running]> on host 2d360e2dfc54
[2023-06-17T21:00:53.253+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nburkett
AIRFLOW_CTX_DAG_ID=showpulse_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_initiate
AIRFLOW_CTX_EXECUTION_DATE=2023-06-17T21:00:52.557322+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-17T21:00:52.557322+00:00
[2023-06-17T21:00:53.255+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-17T21:00:53.255+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd dbt/ticketmaster_transformation && dbt deps --profiles-dir . --target prod']
[2023-06-17T21:00:53.265+0000] {subprocess.py:86} INFO - Output:
[2023-06-17T21:00:53.267+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: dbt/ticketmaster_transformation: No such file or directory
[2023-06-17T21:00:53.267+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-17T21:00:53.277+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-17T21:00:53.280+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=showpulse_dbt_dag, task_id=dbt_initiate, execution_date=20230617T210052, start_date=20230617T210053, end_date=20230617T210053
[2023-06-17T21:00:53.289+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 262 for task dbt_initiate (Bash command failed. The command returned a non-zero exit code 1.; 84)
[2023-06-17T21:00:53.330+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-17T21:00:53.348+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
