[2023-06-23T02:32:57.218+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T02:31:52.899435+00:00 [queued]>
[2023-06-23T02:32:57.226+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T02:31:52.899435+00:00 [queued]>
[2023-06-23T02:32:57.226+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T02:32:57.227+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-23T02:32:57.228+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T02:32:57.239+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-23 02:31:52.899435+00:00
[2023-06-23T02:32:57.243+0000] {standard_task_runner.py:55} INFO - Started process 26294 to run task
[2023-06-23T02:32:57.247+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'showpulse_dbt_dag', 'dbt_run', 'scheduled__2023-06-23T02:31:52.899435+00:00', '--job-id', '2802', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run.py', '--cfg-path', '/tmp/tmpta_aodoz']
[2023-06-23T02:32:57.248+0000] {standard_task_runner.py:83} INFO - Job 2802: Subtask dbt_run
[2023-06-23T02:32:57.317+0000] {task_command.py:389} INFO - Running <TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T02:31:52.899435+00:00 [running]> on host 62cfed75eae1
[2023-06-23T02:32:57.426+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nburkett
AIRFLOW_CTX_DAG_ID=showpulse_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-23T02:31:52.899435+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-23T02:31:52.899435+00:00
[2023-06-23T02:32:57.429+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-23T02:32:57.430+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/ticketmaster_transformation && dbt run']
[2023-06-23T02:32:57.443+0000] {subprocess.py:86} INFO - Output:
[2023-06-23T02:32:59.066+0000] {subprocess.py:93} INFO - [0m02:32:59  Running with dbt=1.5.1
[2023-06-23T02:32:59.813+0000] {subprocess.py:93} INFO - [0m02:32:59  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 356 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-23T02:32:59.816+0000] {subprocess.py:93} INFO - [0m02:32:59
[2023-06-23T02:33:01.003+0000] {subprocess.py:93} INFO - [0m02:33:01  Concurrency: 4 threads (target='dev')
[2023-06-23T02:33:01.006+0000] {subprocess.py:93} INFO - [0m02:33:01
[2023-06-23T02:33:01.020+0000] {subprocess.py:93} INFO - [0m02:33:01  1 of 4 START sql table model twitter_kafka_pyspark_test.distinct_data .......... [RUN]
[2023-06-23T02:33:01.022+0000] {subprocess.py:93} INFO - [0m02:33:01  2 of 4 START sql table model twitter_kafka_pyspark_test.dm_events .............. [RUN]
[2023-06-23T02:33:01.025+0000] {subprocess.py:93} INFO - [0m02:33:01  3 of 4 START sql table model twitter_kafka_pyspark_test.my_first_dbt_model ..... [RUN]
[2023-06-23T02:33:04.142+0000] {subprocess.py:93} INFO - [0m02:33:04  2 of 4 OK created sql table model twitter_kafka_pyspark_test.dm_events ......... [[32mCREATE TABLE (217.0 rows, 32.0 KiB processed)[0m in 3.11s]
[2023-06-23T02:33:04.144+0000] {subprocess.py:93} INFO - [0m02:33:04  3 of 4 OK created sql table model twitter_kafka_pyspark_test.my_first_dbt_model  [[32mCREATE TABLE (2.0 rows, 0 processed)[0m in 3.11s]
[2023-06-23T02:33:04.152+0000] {subprocess.py:93} INFO - [0m02:33:04  4 of 4 START sql view model twitter_kafka_pyspark_test.my_second_dbt_model ..... [RUN]
[2023-06-23T02:33:04.325+0000] {subprocess.py:93} INFO - [0m02:33:04  BigQuery adapter: https://console.cloud.google.com/bigquery?project=global-maxim-338114&j=bq:US:05df7fc2-ffe7-49f3-b95e-7d5df6bb03ab&page=queryresults
[2023-06-23T02:33:04.334+0000] {subprocess.py:93} INFO - [0m02:33:04  1 of 4 ERROR creating sql table model twitter_kafka_pyspark_test.distinct_data . [[31mERROR[0m in 3.31s]
[2023-06-23T02:33:05.041+0000] {subprocess.py:93} INFO - [0m02:33:05  4 of 4 OK created sql view model twitter_kafka_pyspark_test.my_second_dbt_model  [[32mCREATE VIEW (0 processed)[0m in 0.88s]
[2023-06-23T02:33:05.098+0000] {subprocess.py:93} INFO - [0m02:33:05
[2023-06-23T02:33:05.101+0000] {subprocess.py:93} INFO - [0m02:33:05  Finished running 3 table models, 1 view model in 0 hours 0 minutes and 5.28 seconds (5.28s).
[2023-06-23T02:33:05.123+0000] {subprocess.py:93} INFO - [0m02:33:05
[2023-06-23T02:33:05.125+0000] {subprocess.py:93} INFO - [0m02:33:05  [31mCompleted with 1 error and 0 warnings:[0m
[2023-06-23T02:33:05.126+0000] {subprocess.py:93} INFO - [0m02:33:05
[2023-06-23T02:33:05.128+0000] {subprocess.py:93} INFO - [0m02:33:05  [33mDatabase Error in model distinct_data (models/core/distinct_data.sql)[0m
[2023-06-23T02:33:05.129+0000] {subprocess.py:93} INFO - [0m02:33:05    Type not found: FLOAT at [30:27]
[2023-06-23T02:33:05.130+0000] {subprocess.py:93} INFO - [0m02:33:05    compiled Code at target/run/ticketmaster_transformation/models/core/distinct_data.sql
[2023-06-23T02:33:05.132+0000] {subprocess.py:93} INFO - [0m02:33:05
[2023-06-23T02:33:05.133+0000] {subprocess.py:93} INFO - [0m02:33:05  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
[2023-06-23T02:33:05.580+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-23T02:33:05.595+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-23T02:33:05.599+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=showpulse_dbt_dag, task_id=dbt_run, execution_date=20230623T023152, start_date=20230623T023257, end_date=20230623T023305
[2023-06-23T02:33:05.612+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2802 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 26294)
[2023-06-23T02:33:05.628+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-23T02:33:05.643+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
