[2023-06-23T02:25:35.887+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T02:24:31.696804+00:00 [queued]>
[2023-06-23T02:25:35.894+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T02:24:31.696804+00:00 [queued]>
[2023-06-23T02:25:35.894+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T02:25:35.895+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-23T02:25:35.895+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T02:25:35.904+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-23 02:24:31.696804+00:00
[2023-06-23T02:25:35.911+0000] {standard_task_runner.py:55} INFO - Started process 25914 to run task
[2023-06-23T02:25:35.919+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'showpulse_dbt_dag', 'dbt_run', 'scheduled__2023-06-23T02:24:31.696804+00:00', '--job-id', '2770', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run.py', '--cfg-path', '/tmp/tmpmnd4joxh']
[2023-06-23T02:25:35.920+0000] {standard_task_runner.py:83} INFO - Job 2770: Subtask dbt_run
[2023-06-23T02:25:35.982+0000] {task_command.py:389} INFO - Running <TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T02:24:31.696804+00:00 [running]> on host 62cfed75eae1
[2023-06-23T02:25:36.036+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nburkett
AIRFLOW_CTX_DAG_ID=showpulse_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-23T02:24:31.696804+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-23T02:24:31.696804+00:00
[2023-06-23T02:25:36.038+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-23T02:25:36.039+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/ticketmaster_transformation && dbt run']
[2023-06-23T02:25:36.048+0000] {subprocess.py:86} INFO - Output:
[2023-06-23T02:25:37.618+0000] {subprocess.py:93} INFO - [0m02:25:37  Running with dbt=1.5.1
[2023-06-23T02:25:38.251+0000] {subprocess.py:93} INFO - [0m02:25:38  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 356 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-23T02:25:38.254+0000] {subprocess.py:93} INFO - [0m02:25:38
[2023-06-23T02:25:38.929+0000] {subprocess.py:93} INFO - [0m02:25:38  Concurrency: 4 threads (target='dev')
[2023-06-23T02:25:38.932+0000] {subprocess.py:93} INFO - [0m02:25:38
[2023-06-23T02:25:38.949+0000] {subprocess.py:93} INFO - [0m02:25:38  1 of 4 START sql table model twitter_kafka_pyspark_test.distinct_data .......... [RUN]
[2023-06-23T02:25:38.952+0000] {subprocess.py:93} INFO - [0m02:25:38  2 of 4 START sql table model twitter_kafka_pyspark_test.dm_events .............. [RUN]
[2023-06-23T02:25:38.954+0000] {subprocess.py:93} INFO - [0m02:25:38  3 of 4 START sql table model twitter_kafka_pyspark_test.my_first_dbt_model ..... [RUN]
[2023-06-23T02:25:41.499+0000] {subprocess.py:93} INFO - [0m02:25:41  BigQuery adapter: https://console.cloud.google.com/bigquery?project=global-maxim-338114&j=bq:US:ab66bab6-4df8-442f-827e-c284410d0332&page=queryresults
[2023-06-23T02:25:41.514+0000] {subprocess.py:93} INFO - [0m02:25:41  1 of 4 ERROR creating sql table model twitter_kafka_pyspark_test.distinct_data . [[31mERROR[0m in 2.55s]
[2023-06-23T02:25:41.596+0000] {subprocess.py:93} INFO - [0m02:25:41  2 of 4 OK created sql table model twitter_kafka_pyspark_test.dm_events ......... [[32mCREATE TABLE (217.0 rows, 32.0 KiB processed)[0m in 2.63s]
[2023-06-23T02:25:41.600+0000] {subprocess.py:93} INFO - [0m02:25:41  3 of 4 OK created sql table model twitter_kafka_pyspark_test.my_first_dbt_model  [[32mCREATE TABLE (2.0 rows, 0 processed)[0m in 2.64s]
[2023-06-23T02:25:41.605+0000] {subprocess.py:93} INFO - [0m02:25:41  4 of 4 START sql view model twitter_kafka_pyspark_test.my_second_dbt_model ..... [RUN]
[2023-06-23T02:25:42.510+0000] {subprocess.py:93} INFO - [0m02:25:42  4 of 4 OK created sql view model twitter_kafka_pyspark_test.my_second_dbt_model  [[32mCREATE VIEW (0 processed)[0m in 0.90s]
[2023-06-23T02:25:42.610+0000] {subprocess.py:93} INFO - [0m02:25:42
[2023-06-23T02:25:42.612+0000] {subprocess.py:93} INFO - [0m02:25:42  Finished running 3 table models, 1 view model in 0 hours 0 minutes and 4.35 seconds (4.35s).
[2023-06-23T02:25:42.651+0000] {subprocess.py:93} INFO - [0m02:25:42
[2023-06-23T02:25:42.653+0000] {subprocess.py:93} INFO - [0m02:25:42  [31mCompleted with 1 error and 0 warnings:[0m
[2023-06-23T02:25:42.654+0000] {subprocess.py:93} INFO - [0m02:25:42
[2023-06-23T02:25:42.655+0000] {subprocess.py:93} INFO - [0m02:25:42  [33mDatabase Error in model distinct_data (models/core/distinct_data.sql)[0m
[2023-06-23T02:25:42.656+0000] {subprocess.py:93} INFO - [0m02:25:42    Type not found: FLOAT at [46:21]
[2023-06-23T02:25:42.657+0000] {subprocess.py:93} INFO - [0m02:25:42    compiled Code at target/run/ticketmaster_transformation/models/core/distinct_data.sql
[2023-06-23T02:25:42.658+0000] {subprocess.py:93} INFO - [0m02:25:42
[2023-06-23T02:25:42.660+0000] {subprocess.py:93} INFO - [0m02:25:42  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
[2023-06-23T02:25:43.123+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-23T02:25:43.140+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-23T02:25:43.145+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=showpulse_dbt_dag, task_id=dbt_run, execution_date=20230623T022431, start_date=20230623T022535, end_date=20230623T022543
[2023-06-23T02:25:43.157+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2770 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 25914)
[2023-06-23T02:25:43.198+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-23T02:25:43.216+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
