[2023-05-13T22:01:26.926+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ny_taxi_local.create_directory.get_bash_var manual__2023-05-13T22:01:25.474563+00:00 [queued]>
[2023-05-13T22:01:26.938+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ny_taxi_local.create_directory.get_bash_var manual__2023-05-13T22:01:25.474563+00:00 [queued]>
[2023-05-13T22:01:26.939+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T22:01:26.940+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-13T22:01:26.940+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T22:01:26.956+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): create_directory.get_bash_var> on 2023-05-13 22:01:25.474563+00:00
[2023-05-13T22:01:26.963+0000] {standard_task_runner.py:55} INFO - Started process 2056 to run task
[2023-05-13T22:01:26.967+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ny_taxi_local', 'create_directory.get_bash_var', 'manual__2023-05-13T22:01:25.474563+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/fetch_and_upload.py', '--cfg-path', '/tmp/tmpp6w69ymv']
[2023-05-13T22:01:26.970+0000] {standard_task_runner.py:83} INFO - Job 66: Subtask create_directory.get_bash_var
[2023-05-13T22:01:27.055+0000] {task_command.py:389} INFO - Running <TaskInstance: ny_taxi_local.create_directory.get_bash_var manual__2023-05-13T22:01:25.474563+00:00 [running]> on host fdfc81637e26
[2023-05-13T22:01:27.129+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ny_taxi_local
AIRFLOW_CTX_TASK_ID=create_directory.get_bash_var
AIRFLOW_CTX_EXECUTION_DATE=2023-05-13T22:01:25.474563+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-13T22:01:25.474563+00:00
[2023-05-13T22:01:27.133+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_and_upload.py", line 47, in get_bash_var
    bash_command=f'echo "The run_id is: {run_id}"'
NameError: name 'run_id' is not defined
[2023-05-13T22:01:27.144+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=ny_taxi_local, task_id=create_directory.get_bash_var, execution_date=20230513T220125, start_date=20230513T220126, end_date=20230513T220127
[2023-05-13T22:01:27.156+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 66 for task create_directory.get_bash_var (name 'run_id' is not defined; 2056)
[2023-05-13T22:01:27.184+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-13T22:01:27.204+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
