[2023-06-17T21:11:58.944+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_initiate manual__2023-06-17T21:11:58.487136+00:00 [queued]>
[2023-06-17T21:11:58.951+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_initiate manual__2023-06-17T21:11:58.487136+00:00 [queued]>
[2023-06-17T21:11:58.951+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-17T21:11:58.952+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-17T21:11:58.953+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-17T21:11:58.962+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): dbt_initiate> on 2023-06-17 21:11:58.487136+00:00
[2023-06-17T21:11:58.966+0000] {standard_task_runner.py:55} INFO - Started process 94 to run task
[2023-06-17T21:11:58.970+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'showpulse_dbt_dag', 'dbt_initiate', 'manual__2023-06-17T21:11:58.487136+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run.py', '--cfg-path', '/tmp/tmpi0ukp8om']
[2023-06-17T21:11:58.971+0000] {standard_task_runner.py:83} INFO - Job 265: Subtask dbt_initiate
[2023-06-17T21:11:59.024+0000] {task_command.py:389} INFO - Running <TaskInstance: showpulse_dbt_dag.dbt_initiate manual__2023-06-17T21:11:58.487136+00:00 [running]> on host 455b88ed834e
[2023-06-17T21:11:59.078+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nburkett
AIRFLOW_CTX_DAG_ID=showpulse_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_initiate
AIRFLOW_CTX_EXECUTION_DATE=2023-06-17T21:11:58.487136+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-17T21:11:58.487136+00:00
[2023-06-17T21:11:59.079+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-17T21:11:59.080+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd dbt/ticketmaster_transformation && dbt deps --profiles-dir . --target prod']
[2023-06-17T21:11:59.090+0000] {subprocess.py:86} INFO - Output:
[2023-06-17T21:11:59.092+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: dbt/ticketmaster_transformation: No such file or directory
[2023-06-17T21:11:59.093+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-17T21:11:59.104+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-17T21:11:59.107+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=showpulse_dbt_dag, task_id=dbt_initiate, execution_date=20230617T211158, start_date=20230617T211158, end_date=20230617T211159
[2023-06-17T21:11:59.117+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 265 for task dbt_initiate (Bash command failed. The command returned a non-zero exit code 1.; 94)
[2023-06-17T21:11:59.141+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-17T21:11:59.157+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
