[2023-05-13T21:55:59.057+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ny_taxi_local.create_directory.test manual__2023-05-13T21:55:58.227231+00:00 [queued]>
[2023-05-13T21:55:59.064+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ny_taxi_local.create_directory.test manual__2023-05-13T21:55:58.227231+00:00 [queued]>
[2023-05-13T21:55:59.065+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T21:55:59.065+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-13T21:55:59.066+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T21:55:59.076+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): create_directory.test> on 2023-05-13 21:55:58.227231+00:00
[2023-05-13T21:55:59.081+0000] {standard_task_runner.py:55} INFO - Started process 1887 to run task
[2023-05-13T21:55:59.085+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ny_taxi_local', 'create_directory.test', 'manual__2023-05-13T21:55:58.227231+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/fetch_and_upload.py', '--cfg-path', '/tmp/tmp6doelway']
[2023-05-13T21:55:59.088+0000] {standard_task_runner.py:83} INFO - Job 54: Subtask create_directory.test
[2023-05-13T21:55:59.147+0000] {task_command.py:389} INFO - Running <TaskInstance: ny_taxi_local.create_directory.test manual__2023-05-13T21:55:58.227231+00:00 [running]> on host fdfc81637e26
[2023-05-13T21:55:59.198+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ny_taxi_local
AIRFLOW_CTX_TASK_ID=create_directory.test
AIRFLOW_CTX_EXECUTION_DATE=2023-05-13T21:55:58.227231+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-13T21:55:58.227231+00:00
[2023-05-13T21:55:59.200+0000] {logging_mixin.py:137} INFO - TESTING THIS EXAMPLE DAG
[2023-05-13T21:55:59.200+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_and_upload.py", line 40, in test
    {{ run_id }}
NameError: name 'run_id' is not defined
[2023-05-13T21:55:59.210+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=ny_taxi_local, task_id=create_directory.test, execution_date=20230513T215558, start_date=20230513T215559, end_date=20230513T215559
[2023-05-13T21:55:59.217+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 54 for task create_directory.test (name 'run_id' is not defined; 1887)
[2023-05-13T21:55:59.260+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-13T21:55:59.279+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
