[2023-06-23T02:37:22.103+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T02:36:17.891772+00:00 [queued]>
[2023-06-23T02:37:22.111+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T02:36:17.891772+00:00 [queued]>
[2023-06-23T02:37:22.112+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T02:37:22.113+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-23T02:37:22.113+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T02:37:22.121+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-23 02:36:17.891772+00:00
[2023-06-23T02:37:22.126+0000] {standard_task_runner.py:55} INFO - Started process 26582 to run task
[2023-06-23T02:37:22.129+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'showpulse_dbt_dag', 'dbt_run', 'scheduled__2023-06-23T02:36:17.891772+00:00', '--job-id', '2826', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run.py', '--cfg-path', '/tmp/tmpdauuu6mc']
[2023-06-23T02:37:22.131+0000] {standard_task_runner.py:83} INFO - Job 2826: Subtask dbt_run
[2023-06-23T02:37:22.185+0000] {task_command.py:389} INFO - Running <TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T02:36:17.891772+00:00 [running]> on host 62cfed75eae1
[2023-06-23T02:37:22.239+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nburkett
AIRFLOW_CTX_DAG_ID=showpulse_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-23T02:36:17.891772+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-23T02:36:17.891772+00:00
[2023-06-23T02:37:22.240+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-23T02:37:22.241+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/ticketmaster_transformation && dbt run']
[2023-06-23T02:37:22.250+0000] {subprocess.py:86} INFO - Output:
[2023-06-23T02:37:23.583+0000] {subprocess.py:93} INFO - [0m02:37:23  Running with dbt=1.5.1
[2023-06-23T02:37:24.119+0000] {subprocess.py:93} INFO - [0m02:37:24  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 356 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-23T02:37:24.122+0000] {subprocess.py:93} INFO - [0m02:37:24
[2023-06-23T02:37:24.722+0000] {subprocess.py:93} INFO - [0m02:37:24  Concurrency: 4 threads (target='dev')
[2023-06-23T02:37:24.725+0000] {subprocess.py:93} INFO - [0m02:37:24
[2023-06-23T02:37:24.741+0000] {subprocess.py:93} INFO - [0m02:37:24  1 of 4 START sql table model twitter_kafka_pyspark_test.distinct_data .......... [RUN]
[2023-06-23T02:37:24.743+0000] {subprocess.py:93} INFO - [0m02:37:24  2 of 4 START sql table model twitter_kafka_pyspark_test.dm_events .............. [RUN]
[2023-06-23T02:37:24.746+0000] {subprocess.py:93} INFO - [0m02:37:24  3 of 4 START sql table model twitter_kafka_pyspark_test.my_first_dbt_model ..... [RUN]
[2023-06-23T02:37:27.210+0000] {subprocess.py:93} INFO - [0m02:37:27  3 of 4 OK created sql table model twitter_kafka_pyspark_test.my_first_dbt_model  [[32mCREATE TABLE (2.0 rows, 0 processed)[0m in 2.46s]
[2023-06-23T02:37:27.217+0000] {subprocess.py:93} INFO - [0m02:37:27  4 of 4 START sql view model twitter_kafka_pyspark_test.my_second_dbt_model ..... [RUN]
[2023-06-23T02:37:27.231+0000] {subprocess.py:93} INFO - [0m02:37:27  2 of 4 OK created sql table model twitter_kafka_pyspark_test.dm_events ......... [[32mCREATE TABLE (217.0 rows, 32.0 KiB processed)[0m in 2.47s]
[2023-06-23T02:37:27.318+0000] {subprocess.py:93} INFO - [0m02:37:27  BigQuery adapter: https://console.cloud.google.com/bigquery?project=global-maxim-338114&j=bq:US:96bf9ac2-0396-4cc8-adfe-482797b6e8ae&page=queryresults
[2023-06-23T02:37:27.326+0000] {subprocess.py:93} INFO - [0m02:37:27  1 of 4 ERROR creating sql table model twitter_kafka_pyspark_test.distinct_data . [[31mERROR[0m in 2.58s]
[2023-06-23T02:37:28.114+0000] {subprocess.py:93} INFO - [0m02:37:28  4 of 4 OK created sql view model twitter_kafka_pyspark_test.my_second_dbt_model  [[32mCREATE VIEW (0 processed)[0m in 0.89s]
[2023-06-23T02:37:28.189+0000] {subprocess.py:93} INFO - [0m02:37:28
[2023-06-23T02:37:28.191+0000] {subprocess.py:93} INFO - [0m02:37:28  Finished running 3 table models, 1 view model in 0 hours 0 minutes and 4.07 seconds (4.07s).
[2023-06-23T02:37:28.211+0000] {subprocess.py:93} INFO - [0m02:37:28
[2023-06-23T02:37:28.213+0000] {subprocess.py:93} INFO - [0m02:37:28  [31mCompleted with 1 error and 0 warnings:[0m
[2023-06-23T02:37:28.215+0000] {subprocess.py:93} INFO - [0m02:37:28
[2023-06-23T02:37:28.217+0000] {subprocess.py:93} INFO - [0m02:37:28  [33mDatabase Error in model distinct_data (models/core/distinct_data.sql)[0m
[2023-06-23T02:37:28.218+0000] {subprocess.py:93} INFO - [0m02:37:28    Bad double value: \"NaN\"
[2023-06-23T02:37:28.220+0000] {subprocess.py:93} INFO - [0m02:37:28    compiled Code at target/run/ticketmaster_transformation/models/core/distinct_data.sql
[2023-06-23T02:37:28.222+0000] {subprocess.py:93} INFO - [0m02:37:28
[2023-06-23T02:37:28.223+0000] {subprocess.py:93} INFO - [0m02:37:28  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
[2023-06-23T02:37:28.675+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-23T02:37:28.688+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-23T02:37:28.692+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=showpulse_dbt_dag, task_id=dbt_run, execution_date=20230623T023617, start_date=20230623T023722, end_date=20230623T023728
[2023-06-23T02:37:28.703+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2826 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 26582)
[2023-06-23T02:37:28.748+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-23T02:37:28.762+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
