[2023-06-23T02:20:35.172+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T02:19:31.696804+00:00 [queued]>
[2023-06-23T02:20:35.180+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T02:19:31.696804+00:00 [queued]>
[2023-06-23T02:20:35.181+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T02:20:35.181+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-23T02:20:35.182+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T02:20:35.191+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-23 02:19:31.696804+00:00
[2023-06-23T02:20:35.196+0000] {standard_task_runner.py:55} INFO - Started process 25642 to run task
[2023-06-23T02:20:35.199+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'showpulse_dbt_dag', 'dbt_run', 'scheduled__2023-06-23T02:19:31.696804+00:00', '--job-id', '2750', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run.py', '--cfg-path', '/tmp/tmpq_0yn_6s']
[2023-06-23T02:20:35.201+0000] {standard_task_runner.py:83} INFO - Job 2750: Subtask dbt_run
[2023-06-23T02:20:35.260+0000] {task_command.py:389} INFO - Running <TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T02:19:31.696804+00:00 [running]> on host 62cfed75eae1
[2023-06-23T02:20:35.322+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nburkett
AIRFLOW_CTX_DAG_ID=showpulse_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-23T02:19:31.696804+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-23T02:19:31.696804+00:00
[2023-06-23T02:20:35.324+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-23T02:20:35.325+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/ticketmaster_transformation && dbt run']
[2023-06-23T02:20:35.334+0000] {subprocess.py:86} INFO - Output:
[2023-06-23T02:20:36.863+0000] {subprocess.py:93} INFO - [0m02:20:36  Running with dbt=1.5.1
[2023-06-23T02:20:37.490+0000] {subprocess.py:93} INFO - [0m02:20:37  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 356 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-23T02:20:37.493+0000] {subprocess.py:93} INFO - [0m02:20:37
[2023-06-23T02:20:38.110+0000] {subprocess.py:93} INFO - [0m02:20:38  Concurrency: 4 threads (target='dev')
[2023-06-23T02:20:38.112+0000] {subprocess.py:93} INFO - [0m02:20:38
[2023-06-23T02:20:38.123+0000] {subprocess.py:93} INFO - [0m02:20:38  1 of 4 START sql table model twitter_kafka_pyspark_test.distinct_data .......... [RUN]
[2023-06-23T02:20:38.125+0000] {subprocess.py:93} INFO - [0m02:20:38  2 of 4 START sql table model twitter_kafka_pyspark_test.dm_events .............. [RUN]
[2023-06-23T02:20:38.127+0000] {subprocess.py:93} INFO - [0m02:20:38  3 of 4 START sql table model twitter_kafka_pyspark_test.my_first_dbt_model ..... [RUN]
[2023-06-23T02:20:40.552+0000] {subprocess.py:93} INFO - [0m02:20:40  BigQuery adapter: https://console.cloud.google.com/bigquery?project=global-maxim-338114&j=bq:US:0375611e-abe4-4dac-92a3-2cd20026dcd5&page=queryresults
[2023-06-23T02:20:40.563+0000] {subprocess.py:93} INFO - [0m02:20:40  1 of 4 ERROR creating sql table model twitter_kafka_pyspark_test.distinct_data . [[31mERROR[0m in 2.43s]
[2023-06-23T02:20:40.772+0000] {subprocess.py:93} INFO - [0m02:20:40  2 of 4 OK created sql table model twitter_kafka_pyspark_test.dm_events ......... [[32mCREATE TABLE (214.0 rows, 31.5 KiB processed)[0m in 2.64s]
[2023-06-23T02:20:40.928+0000] {subprocess.py:93} INFO - [0m02:20:40  3 of 4 OK created sql table model twitter_kafka_pyspark_test.my_first_dbt_model  [[32mCREATE TABLE (2.0 rows, 0 processed)[0m in 2.79s]
[2023-06-23T02:20:40.933+0000] {subprocess.py:93} INFO - [0m02:20:40  4 of 4 START sql view model twitter_kafka_pyspark_test.my_second_dbt_model ..... [RUN]
[2023-06-23T02:20:41.918+0000] {subprocess.py:93} INFO - [0m02:20:41  4 of 4 OK created sql view model twitter_kafka_pyspark_test.my_second_dbt_model  [[32mCREATE VIEW (0 processed)[0m in 0.98s]
[2023-06-23T02:20:41.989+0000] {subprocess.py:93} INFO - [0m02:20:41
[2023-06-23T02:20:41.991+0000] {subprocess.py:93} INFO - [0m02:20:41  Finished running 3 table models, 1 view model in 0 hours 0 minutes and 4.49 seconds (4.49s).
[2023-06-23T02:20:42.003+0000] {subprocess.py:93} INFO - [0m02:20:42
[2023-06-23T02:20:42.005+0000] {subprocess.py:93} INFO - [0m02:20:42  [31mCompleted with 1 error and 0 warnings:[0m
[2023-06-23T02:20:42.006+0000] {subprocess.py:93} INFO - [0m02:20:42
[2023-06-23T02:20:42.007+0000] {subprocess.py:93} INFO - [0m02:20:42  [33mDatabase Error in model distinct_data (models/core/distinct_data.sql)[0m
[2023-06-23T02:20:42.008+0000] {subprocess.py:93} INFO - [0m02:20:42    CREATE TABLE columns must be named, but column 1 has no name at [14:1]
[2023-06-23T02:20:42.009+0000] {subprocess.py:93} INFO - [0m02:20:42    compiled Code at target/run/ticketmaster_transformation/models/core/distinct_data.sql
[2023-06-23T02:20:42.010+0000] {subprocess.py:93} INFO - [0m02:20:42
[2023-06-23T02:20:42.012+0000] {subprocess.py:93} INFO - [0m02:20:42  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
[2023-06-23T02:20:42.443+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-23T02:20:42.463+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-23T02:20:42.468+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=showpulse_dbt_dag, task_id=dbt_run, execution_date=20230623T021931, start_date=20230623T022035, end_date=20230623T022042
[2023-06-23T02:20:42.479+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2750 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 25642)
[2023-06-23T02:20:42.514+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-23T02:20:42.530+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
