[2023-06-23T01:56:35.642+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T01:55:31.696804+00:00 [queued]>
[2023-06-23T01:56:35.650+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T01:55:31.696804+00:00 [queued]>
[2023-06-23T01:56:35.651+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T01:56:35.652+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-23T01:56:35.652+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T01:56:35.662+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-23 01:55:31.696804+00:00
[2023-06-23T01:56:35.670+0000] {standard_task_runner.py:55} INFO - Started process 24438 to run task
[2023-06-23T01:56:35.674+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'showpulse_dbt_dag', 'dbt_run', 'scheduled__2023-06-23T01:55:31.696804+00:00', '--job-id', '2654', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run.py', '--cfg-path', '/tmp/tmpiogdh_1r']
[2023-06-23T01:56:35.676+0000] {standard_task_runner.py:83} INFO - Job 2654: Subtask dbt_run
[2023-06-23T01:56:35.750+0000] {task_command.py:389} INFO - Running <TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T01:55:31.696804+00:00 [running]> on host 62cfed75eae1
[2023-06-23T01:56:35.813+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nburkett
AIRFLOW_CTX_DAG_ID=showpulse_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-23T01:55:31.696804+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-23T01:55:31.696804+00:00
[2023-06-23T01:56:35.814+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-23T01:56:35.816+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/ticketmaster_transformation && dbt run']
[2023-06-23T01:56:35.826+0000] {subprocess.py:86} INFO - Output:
[2023-06-23T01:56:37.343+0000] {subprocess.py:93} INFO - [0m01:56:37  Running with dbt=1.5.1
[2023-06-23T01:56:37.903+0000] {subprocess.py:93} INFO - [0m01:56:37  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 356 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-23T01:56:37.905+0000] {subprocess.py:93} INFO - [0m01:56:37
[2023-06-23T01:56:38.495+0000] {subprocess.py:93} INFO - [0m01:56:38  Concurrency: 4 threads (target='dev')
[2023-06-23T01:56:38.497+0000] {subprocess.py:93} INFO - [0m01:56:38
[2023-06-23T01:56:38.506+0000] {subprocess.py:93} INFO - [0m01:56:38  1 of 4 START sql table model twitter_kafka_pyspark_test.distinct_data .......... [RUN]
[2023-06-23T01:56:38.508+0000] {subprocess.py:93} INFO - [0m01:56:38  2 of 4 START sql table model twitter_kafka_pyspark_test.dm_events .............. [RUN]
[2023-06-23T01:56:38.510+0000] {subprocess.py:93} INFO - [0m01:56:38  3 of 4 START sql table model twitter_kafka_pyspark_test.my_first_dbt_model ..... [RUN]
[2023-06-23T01:56:40.865+0000] {subprocess.py:93} INFO - [0m01:56:40  3 of 4 OK created sql table model twitter_kafka_pyspark_test.my_first_dbt_model  [[32mCREATE TABLE (2.0 rows, 0 processed)[0m in 2.35s]
[2023-06-23T01:56:40.872+0000] {subprocess.py:93} INFO - [0m01:56:40  4 of 4 START sql view model twitter_kafka_pyspark_test.my_second_dbt_model ..... [RUN]
[2023-06-23T01:56:40.938+0000] {subprocess.py:93} INFO - [0m01:56:40  BigQuery adapter: https://console.cloud.google.com/bigquery?project=global-maxim-338114&j=bq:US:342feb4a-53bc-4aa2-a68b-998c6ec7b895&page=queryresults
[2023-06-23T01:56:40.952+0000] {subprocess.py:93} INFO - [0m01:56:40  2 of 4 ERROR creating sql table model twitter_kafka_pyspark_test.dm_events ..... [[31mERROR[0m in 2.43s]
[2023-06-23T01:56:41.248+0000] {subprocess.py:93} INFO - [0m01:56:41  1 of 4 OK created sql table model twitter_kafka_pyspark_test.distinct_data ..... [[32mCREATE TABLE (1.0 rows, 0 processed)[0m in 2.73s]
[2023-06-23T01:56:41.615+0000] {subprocess.py:93} INFO - [0m01:56:41  4 of 4 OK created sql view model twitter_kafka_pyspark_test.my_second_dbt_model  [[32mCREATE VIEW (0 processed)[0m in 0.74s]
[2023-06-23T01:56:41.634+0000] {subprocess.py:93} INFO - [0m01:56:41
[2023-06-23T01:56:41.635+0000] {subprocess.py:93} INFO - [0m01:56:41  Finished running 3 table models, 1 view model in 0 hours 0 minutes and 3.73 seconds (3.73s).
[2023-06-23T01:56:41.654+0000] {subprocess.py:93} INFO - [0m01:56:41
[2023-06-23T01:56:41.656+0000] {subprocess.py:93} INFO - [0m01:56:41  [31mCompleted with 1 error and 0 warnings:[0m
[2023-06-23T01:56:41.658+0000] {subprocess.py:93} INFO - [0m01:56:41
[2023-06-23T01:56:41.659+0000] {subprocess.py:93} INFO - [0m01:56:41  [33mDatabase Error in model dm_events (models/core/dm_events.sql)[0m
[2023-06-23T01:56:41.661+0000] {subprocess.py:93} INFO - [0m01:56:41    Unrecognized name: event_id at [14:8]
[2023-06-23T01:56:41.662+0000] {subprocess.py:93} INFO - [0m01:56:41    compiled Code at target/run/ticketmaster_transformation/models/core/dm_events.sql
[2023-06-23T01:56:41.664+0000] {subprocess.py:93} INFO - [0m01:56:41
[2023-06-23T01:56:41.665+0000] {subprocess.py:93} INFO - [0m01:56:41  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
[2023-06-23T01:56:42.089+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-23T01:56:42.109+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-23T01:56:42.115+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=showpulse_dbt_dag, task_id=dbt_run, execution_date=20230623T015531, start_date=20230623T015635, end_date=20230623T015642
[2023-06-23T01:56:42.132+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2654 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 24438)
[2023-06-23T01:56:42.184+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-23T01:56:42.205+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
