[2023-06-17T21:46:16.115+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run manual__2023-06-17T21:11:58.487136+00:00 [queued]>
[2023-06-17T21:46:16.121+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run manual__2023-06-17T21:11:58.487136+00:00 [queued]>
[2023-06-17T21:46:16.122+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-17T21:46:16.122+0000] {taskinstance.py:1289} INFO - Starting attempt 5 of 5
[2023-06-17T21:46:16.123+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-17T21:46:16.130+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-17 21:11:58.487136+00:00
[2023-06-17T21:46:16.135+0000] {standard_task_runner.py:55} INFO - Started process 206 to run task
[2023-06-17T21:46:16.138+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'showpulse_dbt_dag', 'dbt_run', 'manual__2023-06-17T21:11:58.487136+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run.py', '--cfg-path', '/tmp/tmp5bxhw4lg']
[2023-06-17T21:46:16.139+0000] {standard_task_runner.py:83} INFO - Job 293: Subtask dbt_run
[2023-06-17T21:46:16.188+0000] {task_command.py:389} INFO - Running <TaskInstance: showpulse_dbt_dag.dbt_run manual__2023-06-17T21:11:58.487136+00:00 [running]> on host e60c8c77cdf9
[2023-06-17T21:46:16.236+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nburkett
AIRFLOW_CTX_DAG_ID=showpulse_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-17T21:11:58.487136+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-17T21:11:58.487136+00:00
[2023-06-17T21:46:16.237+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-17T21:46:16.238+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/ticketmaster_transformation && dbt run']
[2023-06-17T21:46:16.246+0000] {subprocess.py:86} INFO - Output:
[2023-06-17T21:46:17.474+0000] {subprocess.py:93} INFO - [0m21:46:17  Running with dbt=1.5.1
[2023-06-17T21:46:18.557+0000] {subprocess.py:93} INFO - [0m21:46:18  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 356 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-17T21:46:18.560+0000] {subprocess.py:93} INFO - [0m21:46:18
[2023-06-17T21:46:18.568+0000] {subprocess.py:93} INFO - [0m21:46:18
[2023-06-17T21:46:18.569+0000] {subprocess.py:93} INFO - [0m21:46:18  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2023-06-17T21:46:18.570+0000] {subprocess.py:93} INFO - [0m21:46:18  Encountered an error:
[2023-06-17T21:46:18.571+0000] {subprocess.py:93} INFO - Database Error
[2023-06-17T21:46:18.571+0000] {subprocess.py:93} INFO -   [Errno 2] No such file or directory: '/Users/nicburkett/.google/credentials/google_credentials.json'
[2023-06-17T21:46:19.005+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-06-17T21:46:19.016+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-06-17T21:46:19.019+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=showpulse_dbt_dag, task_id=dbt_run, execution_date=20230617T211158, start_date=20230617T214616, end_date=20230617T214619
[2023-06-17T21:46:19.028+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 293 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 206)
[2023-06-17T21:46:19.078+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-17T21:46:19.092+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
