[2023-06-23T02:21:35.816+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T02:20:31.696804+00:00 [queued]>
[2023-06-23T02:21:35.822+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T02:20:31.696804+00:00 [queued]>
[2023-06-23T02:21:35.823+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T02:21:35.823+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-23T02:21:35.824+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T02:21:35.831+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-23 02:20:31.696804+00:00
[2023-06-23T02:21:35.836+0000] {standard_task_runner.py:55} INFO - Started process 25697 to run task
[2023-06-23T02:21:35.839+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'showpulse_dbt_dag', 'dbt_run', 'scheduled__2023-06-23T02:20:31.696804+00:00', '--job-id', '2754', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run.py', '--cfg-path', '/tmp/tmpvazmi0xy']
[2023-06-23T02:21:35.840+0000] {standard_task_runner.py:83} INFO - Job 2754: Subtask dbt_run
[2023-06-23T02:21:35.892+0000] {task_command.py:389} INFO - Running <TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T02:20:31.696804+00:00 [running]> on host 62cfed75eae1
[2023-06-23T02:21:35.943+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nburkett
AIRFLOW_CTX_DAG_ID=showpulse_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-23T02:20:31.696804+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-23T02:20:31.696804+00:00
[2023-06-23T02:21:35.944+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-23T02:21:35.945+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/ticketmaster_transformation && dbt run']
[2023-06-23T02:21:35.955+0000] {subprocess.py:86} INFO - Output:
[2023-06-23T02:21:37.271+0000] {subprocess.py:93} INFO - [0m02:21:37  Running with dbt=1.5.1
[2023-06-23T02:21:37.900+0000] {subprocess.py:93} INFO - [0m02:21:37  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 356 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-23T02:21:37.902+0000] {subprocess.py:93} INFO - [0m02:21:37
[2023-06-23T02:21:38.551+0000] {subprocess.py:93} INFO - [0m02:21:38  Concurrency: 4 threads (target='dev')
[2023-06-23T02:21:38.554+0000] {subprocess.py:93} INFO - [0m02:21:38
[2023-06-23T02:21:38.572+0000] {subprocess.py:93} INFO - [0m02:21:38  1 of 4 START sql table model twitter_kafka_pyspark_test.distinct_data .......... [RUN]
[2023-06-23T02:21:38.575+0000] {subprocess.py:93} INFO - [0m02:21:38  2 of 4 START sql table model twitter_kafka_pyspark_test.dm_events .............. [RUN]
[2023-06-23T02:21:38.578+0000] {subprocess.py:93} INFO - [0m02:21:38  3 of 4 START sql table model twitter_kafka_pyspark_test.my_first_dbt_model ..... [RUN]
[2023-06-23T02:21:39.994+0000] {subprocess.py:93} INFO - [0m02:21:39  BigQuery adapter: https://console.cloud.google.com/bigquery?project=global-maxim-338114&j=bq:US:1fd5b293-a087-4587-899b-1eeb5a81771c&page=queryresults
[2023-06-23T02:21:40.008+0000] {subprocess.py:93} INFO - [0m02:21:40  1 of 4 ERROR creating sql table model twitter_kafka_pyspark_test.distinct_data . [[31mERROR[0m in 1.42s]
[2023-06-23T02:21:41.049+0000] {subprocess.py:93} INFO - [0m02:21:41  3 of 4 OK created sql table model twitter_kafka_pyspark_test.my_first_dbt_model  [[32mCREATE TABLE (2.0 rows, 0 processed)[0m in 2.46s]
[2023-06-23T02:21:41.054+0000] {subprocess.py:93} INFO - [0m02:21:41  4 of 4 START sql view model twitter_kafka_pyspark_test.my_second_dbt_model ..... [RUN]
[2023-06-23T02:21:41.370+0000] {subprocess.py:93} INFO - [0m02:21:41  2 of 4 OK created sql table model twitter_kafka_pyspark_test.dm_events ......... [[32mCREATE TABLE (217.0 rows, 32.0 KiB processed)[0m in 2.78s]
[2023-06-23T02:21:41.775+0000] {subprocess.py:93} INFO - [0m02:21:41  4 of 4 OK created sql view model twitter_kafka_pyspark_test.my_second_dbt_model  [[32mCREATE VIEW (0 processed)[0m in 0.72s]
[2023-06-23T02:21:41.846+0000] {subprocess.py:93} INFO - [0m02:21:41
[2023-06-23T02:21:41.849+0000] {subprocess.py:93} INFO - [0m02:21:41  Finished running 3 table models, 1 view model in 0 hours 0 minutes and 3.94 seconds (3.94s).
[2023-06-23T02:21:41.875+0000] {subprocess.py:93} INFO - [0m02:21:41
[2023-06-23T02:21:41.878+0000] {subprocess.py:93} INFO - [0m02:21:41  [31mCompleted with 1 error and 0 warnings:[0m
[2023-06-23T02:21:41.879+0000] {subprocess.py:93} INFO - [0m02:21:41
[2023-06-23T02:21:41.881+0000] {subprocess.py:93} INFO - [0m02:21:41  [33mDatabase Error in model distinct_data (models/core/distinct_data.sql)[0m
[2023-06-23T02:21:41.883+0000] {subprocess.py:93} INFO - [0m02:21:41    Syntax error: SELECT list must not be empty at [18:3]
[2023-06-23T02:21:41.885+0000] {subprocess.py:93} INFO - [0m02:21:41    compiled Code at target/run/ticketmaster_transformation/models/core/distinct_data.sql
[2023-06-23T02:21:41.886+0000] {subprocess.py:93} INFO - [0m02:21:41
[2023-06-23T02:21:41.888+0000] {subprocess.py:93} INFO - [0m02:21:41  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
[2023-06-23T02:21:42.340+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-23T02:21:42.354+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-23T02:21:42.358+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=showpulse_dbt_dag, task_id=dbt_run, execution_date=20230623T022031, start_date=20230623T022135, end_date=20230623T022142
[2023-06-23T02:21:42.371+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2754 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 25697)
[2023-06-23T02:21:42.421+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-23T02:21:42.436+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
