[2023-06-23T01:51:35.365+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T01:50:31.696804+00:00 [queued]>
[2023-06-23T01:51:35.372+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T01:50:31.696804+00:00 [queued]>
[2023-06-23T01:51:35.373+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T01:51:35.374+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-23T01:51:35.374+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T01:51:35.382+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): dbt_run> on 2023-06-23 01:50:31.696804+00:00
[2023-06-23T01:51:35.386+0000] {standard_task_runner.py:55} INFO - Started process 24194 to run task
[2023-06-23T01:51:35.389+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'showpulse_dbt_dag', 'dbt_run', 'scheduled__2023-06-23T01:50:31.696804+00:00', '--job-id', '2634', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run.py', '--cfg-path', '/tmp/tmp04tl2wu_']
[2023-06-23T01:51:35.390+0000] {standard_task_runner.py:83} INFO - Job 2634: Subtask dbt_run
[2023-06-23T01:51:35.450+0000] {task_command.py:389} INFO - Running <TaskInstance: showpulse_dbt_dag.dbt_run scheduled__2023-06-23T01:50:31.696804+00:00 [running]> on host 62cfed75eae1
[2023-06-23T01:51:35.508+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=nburkett
AIRFLOW_CTX_DAG_ID=showpulse_dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-23T01:50:31.696804+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-23T01:50:31.696804+00:00
[2023-06-23T01:51:35.509+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-23T01:51:35.510+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt/ticketmaster_transformation && dbt run']
[2023-06-23T01:51:35.519+0000] {subprocess.py:86} INFO - Output:
[2023-06-23T01:51:36.970+0000] {subprocess.py:93} INFO - [0m01:51:36  Running with dbt=1.5.1
[2023-06-23T01:51:37.577+0000] {subprocess.py:93} INFO - [0m01:51:37  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 356 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-23T01:51:37.580+0000] {subprocess.py:93} INFO - [0m01:51:37
[2023-06-23T01:51:38.344+0000] {subprocess.py:93} INFO - [0m01:51:38  Concurrency: 4 threads (target='dev')
[2023-06-23T01:51:38.346+0000] {subprocess.py:93} INFO - [0m01:51:38
[2023-06-23T01:51:38.358+0000] {subprocess.py:93} INFO - [0m01:51:38  1 of 4 START sql table model twitter_kafka_pyspark_test.distinct_data .......... [RUN]
[2023-06-23T01:51:38.361+0000] {subprocess.py:93} INFO - [0m01:51:38  2 of 4 START sql table model twitter_kafka_pyspark_test.dm_events .............. [RUN]
[2023-06-23T01:51:38.364+0000] {subprocess.py:93} INFO - [0m01:51:38  3 of 4 START sql table model twitter_kafka_pyspark_test.my_first_dbt_model ..... [RUN]
[2023-06-23T01:51:39.117+0000] {subprocess.py:93} INFO - [0m01:51:39  1 of 4 ERROR creating sql table model twitter_kafka_pyspark_test.distinct_data . [[31mERROR[0m in 0.75s]
[2023-06-23T01:51:39.149+0000] {subprocess.py:93} INFO - [0m01:51:39  2 of 4 ERROR creating sql table model twitter_kafka_pyspark_test.dm_events ..... [[31mERROR[0m in 0.78s]
[2023-06-23T01:51:41.034+0000] {subprocess.py:93} INFO - [0m01:51:41  3 of 4 OK created sql table model twitter_kafka_pyspark_test.my_first_dbt_model  [[32mCREATE TABLE (2.0 rows, 0 processed)[0m in 2.66s]
[2023-06-23T01:51:41.041+0000] {subprocess.py:93} INFO - [0m01:51:41  4 of 4 START sql view model twitter_kafka_pyspark_test.my_second_dbt_model ..... [RUN]
[2023-06-23T01:51:42.049+0000] {subprocess.py:93} INFO - [0m01:51:42  4 of 4 OK created sql view model twitter_kafka_pyspark_test.my_second_dbt_model  [[32mCREATE VIEW (0 processed)[0m in 1.00s]
[2023-06-23T01:51:42.111+0000] {subprocess.py:93} INFO - [0m01:51:42
[2023-06-23T01:51:42.113+0000] {subprocess.py:93} INFO - [0m01:51:42  Finished running 3 table models, 1 view model in 0 hours 0 minutes and 4.53 seconds (4.53s).
[2023-06-23T01:51:42.134+0000] {subprocess.py:93} INFO - [0m01:51:42
[2023-06-23T01:51:42.136+0000] {subprocess.py:93} INFO - [0m01:51:42  [31mCompleted with 2 errors and 0 warnings:[0m
[2023-06-23T01:51:42.138+0000] {subprocess.py:93} INFO - [0m01:51:42
[2023-06-23T01:51:42.139+0000] {subprocess.py:93} INFO - [0m01:51:42  [33mRuntime Error in model distinct_data (models/core/distinct_data.sql)[0m
[2023-06-23T01:51:42.140+0000] {subprocess.py:93} INFO - [0m01:51:42    404 Not found: Table global-maxim-338114:twitter_kafka_pyspark_test.kafka_pyspark was not found in location US
[2023-06-23T01:51:42.141+0000] {subprocess.py:93} INFO - [0m01:51:42
[2023-06-23T01:51:42.142+0000] {subprocess.py:93} INFO - [0m01:51:42    Location: US
[2023-06-23T01:51:42.143+0000] {subprocess.py:93} INFO - [0m01:51:42    Job ID: b30a2e1d-2c5f-474b-bbed-8da2fe36b924
[2023-06-23T01:51:42.144+0000] {subprocess.py:93} INFO - [0m01:51:42
[2023-06-23T01:51:42.145+0000] {subprocess.py:93} INFO - [0m01:51:42
[2023-06-23T01:51:42.147+0000] {subprocess.py:93} INFO - [0m01:51:42  [33mRuntime Error in model dm_events (models/core/dm_events.sql)[0m
[2023-06-23T01:51:42.148+0000] {subprocess.py:93} INFO - [0m01:51:42    404 Not found: Table global-maxim-338114:twitter_kafka_pyspark_test.kafka_pyspark was not found in location US
[2023-06-23T01:51:42.149+0000] {subprocess.py:93} INFO - [0m01:51:42
[2023-06-23T01:51:42.150+0000] {subprocess.py:93} INFO - [0m01:51:42    Location: US
[2023-06-23T01:51:42.151+0000] {subprocess.py:93} INFO - [0m01:51:42    Job ID: d502fd15-e35c-4c93-9839-f4908fc69b89
[2023-06-23T01:51:42.153+0000] {subprocess.py:93} INFO - [0m01:51:42
[2023-06-23T01:51:42.154+0000] {subprocess.py:93} INFO - [0m01:51:42
[2023-06-23T01:51:42.156+0000] {subprocess.py:93} INFO - [0m01:51:42  Done. PASS=2 WARN=0 ERROR=2 SKIP=0 TOTAL=4
[2023-06-23T01:51:42.542+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-23T01:51:42.556+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-23T01:51:42.560+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=showpulse_dbt_dag, task_id=dbt_run, execution_date=20230623T015031, start_date=20230623T015135, end_date=20230623T015142
[2023-06-23T01:51:42.572+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2634 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 24194)
[2023-06-23T01:51:42.604+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-23T01:51:42.620+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
