[2023-05-13T22:01:23.987+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ny_taxi_local.create_directory.get_bash_var manual__2023-05-13T21:53:10.179136+00:00 [queued]>
[2023-05-13T22:01:23.993+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ny_taxi_local.create_directory.get_bash_var manual__2023-05-13T21:53:10.179136+00:00 [queued]>
[2023-05-13T22:01:23.993+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T22:01:23.994+0000] {taskinstance.py:1289} INFO - Starting attempt 3 of 3
[2023-05-13T22:01:23.994+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T22:01:24.003+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): create_directory.get_bash_var> on 2023-05-13 21:53:10.179136+00:00
[2023-05-13T22:01:24.008+0000] {standard_task_runner.py:55} INFO - Started process 2041 to run task
[2023-05-13T22:01:24.012+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ny_taxi_local', 'create_directory.get_bash_var', 'manual__2023-05-13T21:53:10.179136+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/fetch_and_upload.py', '--cfg-path', '/tmp/tmpaxdg1dv0']
[2023-05-13T22:01:24.014+0000] {standard_task_runner.py:83} INFO - Job 64: Subtask create_directory.get_bash_var
[2023-05-13T22:01:24.069+0000] {task_command.py:389} INFO - Running <TaskInstance: ny_taxi_local.create_directory.get_bash_var manual__2023-05-13T21:53:10.179136+00:00 [running]> on host fdfc81637e26
[2023-05-13T22:01:24.119+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ny_taxi_local
AIRFLOW_CTX_TASK_ID=create_directory.get_bash_var
AIRFLOW_CTX_EXECUTION_DATE=2023-05-13T21:53:10.179136+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-13T21:53:10.179136+00:00
[2023-05-13T22:01:24.121+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_and_upload.py", line 47, in get_bash_var
    bash_command=f'echo "The run_id is: {run_id}"'
NameError: name 'run_id' is not defined
[2023-05-13T22:01:24.130+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=ny_taxi_local, task_id=create_directory.get_bash_var, execution_date=20230513T215310, start_date=20230513T220123, end_date=20230513T220124
[2023-05-13T22:01:24.137+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 64 for task create_directory.get_bash_var (name 'run_id' is not defined; 2041)
[2023-05-13T22:01:24.189+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-13T22:01:24.205+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
