[2023-05-13T20:46:28.921+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ny_taxi_local.create_directoriesand_download.bash_get_data manual__2023-05-13T20:46:27.366457+00:00 [queued]>
[2023-05-13T20:46:28.930+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ny_taxi_local.create_directoriesand_download.bash_get_data manual__2023-05-13T20:46:27.366457+00:00 [queued]>
[2023-05-13T20:46:28.931+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T20:46:28.931+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-13T20:46:28.932+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T20:46:28.943+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): create_directoriesand_download.bash_get_data> on 2023-05-13 20:46:27.366457+00:00
[2023-05-13T20:46:28.948+0000] {standard_task_runner.py:55} INFO - Started process 108 to run task
[2023-05-13T20:46:28.958+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ny_taxi_local', 'create_directoriesand_download.bash_get_data', 'manual__2023-05-13T20:46:27.366457+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/fetch_and_upload.py', '--cfg-path', '/tmp/tmpbhmrs3mv']
[2023-05-13T20:46:28.961+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask create_directoriesand_download.bash_get_data
[2023-05-13T20:46:29.038+0000] {task_command.py:389} INFO - Running <TaskInstance: ny_taxi_local.create_directoriesand_download.bash_get_data manual__2023-05-13T20:46:27.366457+00:00 [running]> on host fdfc81637e26
[2023-05-13T20:46:29.109+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ny_taxi_local
AIRFLOW_CTX_TASK_ID=create_directoriesand_download.bash_get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-05-13T20:46:27.366457+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-13T20:46:27.366457+00:00
[2023-05-13T20:46:29.111+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-13T20:46:29.111+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.csv.gz > ../data/yellow/2021/{ run_id }_yellow_tripdata_2021-01.csv.gz']
[2023-05-13T20:46:29.123+0000] {subprocess.py:86} INFO - Output:
[2023-05-13T20:46:29.128+0000] {subprocess.py:93} INFO - /bin/bash: line 1: ../data/yellow/2021/{: No such file or directory
[2023-05-13T20:46:29.129+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-05-13T20:46:29.143+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_and_upload.py", line 39, in bash_get_data
    return op.execute(context={})
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-13T20:46:29.148+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=ny_taxi_local, task_id=create_directoriesand_download.bash_get_data, execution_date=20230513T204627, start_date=20230513T204628, end_date=20230513T204629
[2023-05-13T20:46:29.156+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 10 for task create_directoriesand_download.bash_get_data (Bash command failed. The command returned a non-zero exit code 1.; 108)
[2023-05-13T20:46:29.166+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-13T20:46:29.185+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
