[2023-05-13T20:50:04.422+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ny_taxi_local.create_directory.create_directory manual__2023-05-13T20:50:03.503946+00:00 [queued]>
[2023-05-13T20:50:04.429+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ny_taxi_local.create_directory.create_directory manual__2023-05-13T20:50:03.503946+00:00 [queued]>
[2023-05-13T20:50:04.430+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T20:50:04.430+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-13T20:50:04.431+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-13T20:50:04.440+0000] {taskinstance.py:1309} INFO - Executing <Task(_PythonDecoratedOperator): create_directory.create_directory> on 2023-05-13 20:50:03.503946+00:00
[2023-05-13T20:50:04.445+0000] {standard_task_runner.py:55} INFO - Started process 192 to run task
[2023-05-13T20:50:04.449+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ny_taxi_local', 'create_directory.create_directory', 'manual__2023-05-13T20:50:03.503946+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/fetch_and_upload.py', '--cfg-path', '/tmp/tmp6uh_9whd']
[2023-05-13T20:50:04.452+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask create_directory.create_directory
[2023-05-13T20:50:04.531+0000] {task_command.py:389} INFO - Running <TaskInstance: ny_taxi_local.create_directory.create_directory manual__2023-05-13T20:50:03.503946+00:00 [running]> on host fdfc81637e26
[2023-05-13T20:50:04.582+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ny_taxi_local
AIRFLOW_CTX_TASK_ID=create_directory.create_directory
AIRFLOW_CTX_EXECUTION_DATE=2023-05-13T20:50:03.503946+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-13T20:50:03.503946+00:00
[2023-05-13T20:50:04.584+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_and_upload.py", line 26, in create_directory
    os.makedirs(path)
  File "/usr/local/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '../data'
[2023-05-13T20:50:04.595+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=ny_taxi_local, task_id=create_directory.create_directory, execution_date=20230513T205003, start_date=20230513T205004, end_date=20230513T205004
[2023-05-13T20:50:04.602+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 12 for task create_directory.create_directory ([Errno 13] Permission denied: '../data'; 192)
[2023-05-13T20:50:04.623+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-13T20:50:04.643+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
